#! /bin/bash
#
# Install KFC's service and timer
#
# June-2023, Pat Welch, pat@mousebrains.com

myPath=`dirname $0`

$myPath/TPWUtils/install.py \
	--verbose \
	--service=Copernicus.service \
	--service=earthdata.service \
	$*
