#! /bin/bash
#
# Install rclone mount service for GoogleDrive
#
# July-2023, Pat Welch, pat@mousebrains.com

myPath=`dirname $0`

$myPath/TPWUtils/install.py \
	--verbose \
	--service=ARCTERXGDrive.service \
	$*
