#! /bin/bash
#
# Install WaveGlider service and timer
#
# June-2023, Pat Welch, pat@mousebrains.com

myPath=`dirname $0`

$myPath/TPWUtils/install.py \
	--verbose \
	--service=WaveGlider.service \
	--service=WG_Luca.service \
	$*

