#! /bin/bash
#
# Install Ship data to DB service and timer
#
# June-2023, Pat Welch, pat@mousebrains.com

myPath=`dirname $0`

$myPath/TPWUtils/install.py \
	--verbose \
	--service=Ship2DB.service \
	$*
