#! /bin/bash
#
# Install Slocum glider service and timer
#
# June-2023, Pat Welch, pat@mousebrains.com

myPath=`dirname $0`

$myPath/TPWUtils/install.py \
	--verbose \
	--service=Slocum.service \
	$*
